
ACCOUNT_LOGIN = 'EVAL_VAAS'
APPLICATION_LOGIN = 'EVAL_YYYYYYY'
APPLICATION_PASSWORD = 'XXXXXXXX'

SERVICE_URL = 'http://vaas.acapela-group.com/Services/Synthesizer'
QUALITY = '22k'  -- 22k, 8k, 8ka, 8kmu
TTS_ENGINE = 'ACAPELA'  -- FLITE, CEPSTRAL, ACAPELA
ACAPELA_GENDER = 'W'
ACAPELA_INTONATION = 'NORMAL'
